spring.application.name=UsuarioCanchaReserva
jwt.secret=dGVzdFNlY3JldEtleVRoYXRJc1ZlcnlMb25nRW5vdWdoRm9ySG1hYzI1Ng==
#configuracion database y jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/sistem
spring.datasource.username=postgres
spring.datasource.password=santi0987#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
